// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSS.Models;

namespace PSS.Migrations
{
    [DbContext(typeof(PSSContext_old))]
    [Migration("20190226153201_Proyectos3")]
    partial class Proyectos3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PSS.Models.Proyectos", b =>
                {
                    b.Property<int>("IdEmpresa");

                    b.Property<bool>("AccesosRodados");

                    b.Property<bool>("Alcantarillado");

                    b.Property<string>("Autor")
                        .HasMaxLength(255);

                    b.Property<string>("AutorProyecto")
                        .HasMaxLength(255);

                    b.Property<string>("CaracteristicasTerreno");

                    b.Property<bool>("CirculacionesPeatonales");

                    b.Property<string>("CiudadContratista")
                        .HasMaxLength(255);

                    b.Property<string>("CiudadObra")
                        .HasMaxLength(255);

                    b.Property<string>("Cliente")
                        .HasMaxLength(255);

                    b.Property<string>("Climatologia");

                    b.Property<bool>("ConduccionesGas");

                    b.Property<string>("Contratista")
                        .HasMaxLength(255);

                    b.Property<string>("CpContratista")
                        .HasMaxLength(5);

                    b.Property<string>("CpObra")
                        .HasMaxLength(50);

                    b.Property<string>("CssfaseProyecto")
                        .HasColumnName("CSSFaseProyecto")
                        .HasMaxLength(255);

                    b.Property<string>("DescripcionLugar");

                    b.Property<string>("DescripcionObra");

                    b.Property<string>("DireccionContratista")
                        .HasMaxLength(255);

                    b.Property<string>("DireccionObra")
                        .HasMaxLength(255);

                    b.Property<int?>("Duracion");

                    b.Property<string>("Encargado")
                        .HasMaxLength(255);

                    b.Property<int>("IdObra")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("InstProviAreasAux");

                    b.Property<string>("JefeObra")
                        .HasMaxLength(255);

                    b.Property<bool>("LinElectAereas");

                    b.Property<bool>("LinElectEnterradas");

                    b.Property<string>("LinderoEste")
                        .HasMaxLength(255);

                    b.Property<string>("LinderoNorte")
                        .HasMaxLength(255);

                    b.Property<string>("LinderoOeste")
                        .HasMaxLength(255);

                    b.Property<string>("LinderoSur")
                        .HasMaxLength(255);

                    b.Property<bool>("LineasTelefonicas");

                    b.Property<string>("NombreObra")
                        .HasMaxLength(255);

                    b.Property<string>("NumOt")
                        .HasMaxLength(50);

                    b.Property<int?>("NumTrabajadores");

                    b.Property<string>("PemPec")
                        .HasColumnName("PEM_PEC")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Presupuesto")
                        .HasColumnType("money");

                    b.Property<string>("Promotor")
                        .HasMaxLength(255);

                    b.Property<string>("ProvinciaContratista")
                        .HasMaxLength(255);

                    b.Property<string>("ProvinciaObra")
                        .HasMaxLength(255);

                    b.Property<string>("RecursoPreventivo")
                        .HasMaxLength(255);

                    b.Property<string>("Superficie")
                        .HasMaxLength(50);

                    b.Property<string>("Tecnico")
                        .HasMaxLength(255);

                    b.Property<string>("TipoEstudio")
                        .HasMaxLength(50);

                    b.Property<string>("TipoObra")
                        .HasMaxLength(255);

                    b.Property<string>("TraficoRodado");

                    b.Property<bool>("Transformadores");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Proyectos");
                });
#pragma warning restore 612, 618
        }
    }
}
